apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aire.fullname" . }}
  namespace: {{ include "aire.namespace" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "aire.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "aire.fullname" . }}

    spec:
      containers:
      - name: {{ .Values.deploy.service }}

        image: {{ include "aire.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        envFrom:
        {{- if .Values.configMap.enabled }}
        - configMapRef:
            name: {{ .Values.deploy.project }}-{{ .Values.deploy.instance }}-config
        {{- end }}

        ports:
        - containerPort: {{ .Values.service.port }}