apiVersion: v1
kind: Service
metadata:
  name: {{ include "aire.fullname" . }}
  namespace: {{ include "aire.namespace" . }}

spec:
  selector:
    app: {{ include "aire.appname" . }}

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}