apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "aire.backend.name" . }}
  namespace: {{ include "aire.namespace" . }}

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.serviceAccount.awsAccountId }}:role/{{ .Values.serviceAccount.IamRole }}