{{- if .Values.redis.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: redis-{{ .Values.deploy.instance }}
  namespace: {{ include "aire.namespace" . }}

spec:
  selector:
    app: redis-{{ .Values.deploy.instance }}

  ports:
  - port: 6379
    targetPort: 6379

{{- end }}