{{- if .Values.redis.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ include "aire.redis.name" . }}
  namespace: {{ include "aire.namespace" . }}

spec:
  selector:
    app: {{ include "aire.redis.name" . }}

  ports:
  - port: 6379
    targetPort: 6379

{{- end }}