apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-app.instanceId" . }}-config
  namespace: {{ include "base-app.namespace" . }}    
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
data:
  HOSTNAME: "{{ include "base-app.hostname" . }}"
