{{- if .Values.efs.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-{{ include "base-app.appGroup" . }}
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-appdata-{{ include "base-app.appGroup" . }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-{{ include "base-app.appGroup" . }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-011c0f1b9c1783449:/appdata/{{ .Values.deploy.project }}/{{ .Values.deploy.environmentGroup }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-appdata-{{ include "base-app.appGroup" . }}
  namespace: enerindev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-{{ include "base-app.appGroup" . }}
  resources:
    requests:
      storage: 5Gi
{{ end }}
