{{- if .Values.redis.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "base-app.namespace" . }}
  name: {{ include "base-app.serviceId" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service-type: redis 
      {{- include "base-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ include "base-app.namespace" . }}
      labels:
        app.kubernetes.io/service-type: redis             
        {{- include "base-app.labels" . | nindent 8 }}
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "base-app.namespace" . }}    
  name: {{ include "base-app.serviceId" . }}-redis
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/service-type: redis     
    {{- include "base-app.selectorLabels" . | nindent 4 }}      
{{- end }}



