{{- if .Values.aws_secrets.enabled -}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ include "base-app.namespace" . }}
  name: {{ include "base-app.serviceId" . }}-secrets
spec:
  provider: aws
  parameters:
    objects: 
      {{- range .Values.aws_secrets.entries }}
      - objectName: {{ .path }}
        objectType: "secretsmanager"
        objectAlias: {{ .alias }}
      {{- end }}
{{- end }}
