{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "base-app.namespace" . }}    
  name: {{ include "base-app.serviceAccountName" . }}
  labels:
    {{- include "base-app.mainlabels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.serviceAccount.awsAccountId }}:role/{{ include "base-app.iamRoleName" . }}      
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
















