apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "base-app.namespace" . }}    
  name: {{ include "base-app.serviceId" . }}
  labels:
    {{- include "base-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: appport
  selector:
    app.kubernetes.io/service-type: public     
    {{- include "base-app.selectorLabels" . | nindent 4 }}
